/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: [
    "@gc-ai-os/shared-types",
    "@gc-ai-os/model-provider",
    "@gc-ai-os/agents-core",
    "@gc-ai-os/orchestrator",
    "@gc-ai-os/memory",
    "@gc-ai-os/security",
    "@gc-ai-os/runtime",
    "@gc-ai-os/telemetry",
    "@gc-ai-os/executive",
    "@gc-ai-os/goals",
    "@gc-ai-os/factory",
    "@gc-ai-os/connectors",
    "@gc-ai-os/metrics",
    "@gc-ai-os/executive-brain",
    "@gc-ai-os/people",
    "@gc-ai-os/ceo-agent",
    "@gc-ai-os/cto-agent",
    "@gc-ai-os/frontend-agent",
    "@gc-ai-os/backend-agent",
    "@gc-ai-os/supabase-agent",
    "@gc-ai-os/devops-agent",
    "@gc-ai-os/qa-agent",
    "@gc-ai-os/marketing-agent",
    "@gc-ai-os/commercial-agent",
    "@gc-ai-os/support-agent",
    "@gc-ai-os/finance-agent",
    "@gc-ai-os/content-agent",
    "@gc-ai-os/research-agent",
    "@gc-ai-os/data-agent",
    "@gc-ai-os/legal-agent",
    "@gc-ai-os/automation-agent",
    "@gc-ai-os/security-agent",
    "@gc-ai-os/customer-success-agent",
    "@gc-ai-os/recruitment-agent",
  ],
};

export default nextConfig;
