import { randomUUID } from "node:crypto";
import type { Report } from "@/lib/audit-engine/types";
import type { PreviewBlueprint } from "./blueprint-schema";
import type { PipelineState, PreviewWork, StageName } from "./pipeline-types";
import type { VerifiedCompanyProfile } from "./types";

/**
 * Persistence of previews. Production: the `gc_site_previews` table in the
 * audit Supabase project, reached ONLY through SECURITY DEFINER RPCs gated by
 * the same server secret as the audit leads (the table itself has RLS on and
 * no policy). Development/tests: an in-memory store with the same semantics.
 */

export type PreviewStatus = "running" | "needs_input" | "ready" | "failed";

export type PreviewInput = {
  companyName: string;
  cityHint?: string;
  /** Origin the visitor started from (validated), used for the e-mail link. */
  origin?: string;
};

export type PreviewRow = {
  id: string;
  status: PreviewStatus;
  stage: StageName;
  needs: "city" | "site" | null;
  company_name: string;
  siren: string | null;
  official_domain: string | null;
  fingerprint: string | null;
  input: PreviewInput;
  attribution: Record<string, string>;
  pipeline: PipelineState;
  work: PreviewWork;
  company_profile: VerifiedCompanyProfile | null;
  audit_report: Report | null;
  preview_blueprint: PreviewBlueprint | null;
  email: string | null;
  notified_at: string | null;
  lead_id: string | null;
  engine_version: string;
  error_code: string | null;
  created_at: string;
  updated_at: string;
  ready_at: string | null;
  expires_at: string | null;
};

export type PreviewPatch = Partial<
  Pick<
    PreviewRow,
    | "status"
    | "stage"
    | "needs"
    | "company_name"
    | "siren"
    | "official_domain"
    | "fingerprint"
    | "pipeline"
    | "work"
    | "company_profile"
    | "audit_report"
    | "preview_blueprint"
    | "engine_version"
    | "error_code"
    | "ready_at"
    | "expires_at"
  >
>;

export type CreatePreview = {
  /** Generated by the server (UUID v4) so the token hash can be stored at creation. */
  id: string;
  idempotencyKey: string;
  tokenHash: string;
  companyName: string;
  input: PreviewInput;
  attribution: Record<string, string>;
  pipeline: PipelineState;
  work: PreviewWork;
  stage: StageName;
  engineVersion: string;
};

export interface PreviewStore {
  readonly kind: "supabase" | "memory";
  /** Idempotent on `idempotencyKey`: a replay returns the preview already created. */
  create(input: CreatePreview): Promise<PreviewRow | null>;
  get(id: string): Promise<PreviewRow | null>;
  /** Takes the advancing lease if free (or expired). Returns the row either way. */
  claim(id: string, leaseMs: number): Promise<{ row: PreviewRow; leaseId: string | null } | null>;
  /** Writes the patch only while holding the lease, then releases it. */
  save(id: string, leaseId: string, patch: PreviewPatch): Promise<boolean>;
  /** Most recent preview for a fingerprint, among the given statuses, younger than maxAgeHours. */
  findByFingerprint(fingerprint: string, statuses: PreviewStatus[], maxAgeHours: number, excludeId?: string): Promise<PreviewRow | null>;
  /** Previews still running, plus ready ones whose e-mail is still owed — for the background worker. */
  listActive(limit: number): Promise<PreviewRow[]>;
  setEmail(id: string, email: string, leadId: string | null): Promise<boolean>;
  /** True only the first time: guards the ready e-mail against double sends. */
  markNotified(id: string): Promise<boolean>;
}

// ---------------------------------------------------------------------------
// Supabase (RPC)

type RpcConfig = { url: string; key: string; secret: string };

function rpcConfig(): RpcConfig | null {
  const url = process.env.GC_AUDIT_SUPABASE_URL || "";
  const key = process.env.GC_AUDIT_SUPABASE_KEY || "";
  const secret = process.env.GC_AUDIT_RPC_SECRET || "";
  return url && key && secret ? { url, key, secret } : null;
}

async function rpc<T>(cfg: RpcConfig, name: string, args: Record<string, unknown>): Promise<T | null> {
  try {
    const response = await fetch(`${cfg.url}/rest/v1/rpc/${name}`, {
      method: "POST",
      headers: { apikey: cfg.key, Authorization: `Bearer ${cfg.key}`, "Content-Type": "application/json" },
      body: JSON.stringify({ p_secret: cfg.secret, ...args }),
      cache: "no-store",
      signal: AbortSignal.timeout(4_000),
    });
    const text = await response.text();
    if (!response.ok) {
      console.error("[preview/store] RPC failed:", name, response.status, text.slice(0, 300));
      return null;
    }
    return text ? (JSON.parse(text) as T) : null;
  } catch (error) {
    console.error("[preview/store] RPC error:", name, error instanceof Error ? error.name : "unknown");
    return null;
  }
}

function first(rows: PreviewRow[] | PreviewRow | null): PreviewRow | null {
  if (!rows) return null;
  return Array.isArray(rows) ? rows[0] ?? null : rows;
}

export class SupabasePreviewStore implements PreviewStore {
  readonly kind = "supabase" as const;
  constructor(private readonly cfg: RpcConfig) {}

  async create(input: CreatePreview) {
    return first(
      await rpc<PreviewRow[]>(this.cfg, "gc_preview_create", {
        p_id: input.id,
        p_idempotency_key: input.idempotencyKey,
        p_token_hash: input.tokenHash,
        p_company_name: input.companyName,
        p_input: input.input,
        p_attribution: input.attribution,
        p_pipeline: input.pipeline,
        p_work: input.work,
        p_stage: input.stage,
        p_engine_version: input.engineVersion,
      })
    );
  }

  async get(id: string) {
    return first(await rpc<PreviewRow[]>(this.cfg, "gc_preview_get", { p_id: id }));
  }

  async claim(id: string, leaseMs: number) {
    const result = await rpc<{ claimed: boolean; lease_id: string | null; row: PreviewRow | null }>(this.cfg, "gc_preview_claim", {
      p_id: id,
      p_lease_ms: leaseMs,
    });
    if (!result?.row) return null;
    return { row: result.row, leaseId: result.claimed ? result.lease_id : null };
  }

  async save(id: string, leaseId: string, patch: PreviewPatch) {
    return (await rpc<boolean>(this.cfg, "gc_preview_save", { p_id: id, p_lease_id: leaseId, p_patch: patch })) === true;
  }

  async findByFingerprint(fingerprint: string, statuses: PreviewStatus[], maxAgeHours: number, excludeId?: string) {
    return first(
      await rpc<PreviewRow[]>(this.cfg, "gc_preview_find", {
        p_fingerprint: fingerprint,
        p_statuses: statuses,
        p_max_age_hours: maxAgeHours,
        p_exclude_id: excludeId ?? null,
      })
    );
  }

  async listActive(limit: number) {
    return (await rpc<PreviewRow[]>(this.cfg, "gc_preview_list_active", { p_limit: limit })) ?? [];
  }

  async setEmail(id: string, email: string, leadId: string | null) {
    return (await rpc<boolean>(this.cfg, "gc_preview_set_email", { p_id: id, p_email: email, p_lead_id: leadId })) === true;
  }

  async markNotified(id: string) {
    return (await rpc<boolean>(this.cfg, "gc_preview_mark_notified", { p_id: id })) === true;
  }
}

// ---------------------------------------------------------------------------
// Memory (development and tests only)

type MemoryRow = PreviewRow & { idempotency_key: string; token_hash: string; lease_id: string | null; lease_until: number };

export class MemoryPreviewStore implements PreviewStore {
  readonly kind = "memory" as const;
  private rows = new Map<string, MemoryRow>();

  private clone(row: MemoryRow): PreviewRow {
    // Mirrors the JSON round trip of the real store: callers never share references.
    const { idempotency_key: _k, token_hash: _t, lease_id: _l, lease_until: _u, ...rest } = row;
    void _k;
    void _t;
    void _l;
    void _u;
    return JSON.parse(JSON.stringify(rest)) as PreviewRow;
  }

  async create(input: CreatePreview) {
    for (const row of this.rows.values()) if (row.idempotency_key === input.idempotencyKey) return this.clone(row);
    const now = new Date().toISOString();
    const row: MemoryRow = {
      id: input.id,
      status: "running",
      stage: input.stage,
      needs: null,
      company_name: input.companyName,
      siren: null,
      official_domain: null,
      fingerprint: null,
      input: input.input,
      attribution: input.attribution,
      pipeline: input.pipeline,
      work: input.work,
      company_profile: null,
      audit_report: null,
      preview_blueprint: null,
      email: null,
      notified_at: null,
      lead_id: null,
      engine_version: input.engineVersion,
      error_code: null,
      created_at: now,
      updated_at: now,
      ready_at: null,
      expires_at: new Date(Date.now() + 30 * 86_400_000).toISOString(),
      idempotency_key: input.idempotencyKey,
      token_hash: input.tokenHash,
      lease_id: null,
      lease_until: 0,
    };
    this.rows.set(row.id, JSON.parse(JSON.stringify(row)));
    return this.clone(row);
  }

  async get(id: string) {
    const row = this.rows.get(id);
    return row ? this.clone(row) : null;
  }

  async claim(id: string, leaseMs: number) {
    const row = this.rows.get(id);
    if (!row) return null;
    if (row.lease_until > Date.now()) return { row: this.clone(row), leaseId: null };
    row.lease_id = randomUUID();
    row.lease_until = Date.now() + leaseMs;
    return { row: this.clone(row), leaseId: row.lease_id };
  }

  async save(id: string, leaseId: string, patch: PreviewPatch) {
    const row = this.rows.get(id);
    if (!row || row.lease_id !== leaseId) return false;
    Object.assign(row, JSON.parse(JSON.stringify(patch)), { updated_at: new Date().toISOString(), lease_id: null, lease_until: 0 });
    return true;
  }

  async findByFingerprint(fingerprint: string, statuses: PreviewStatus[], maxAgeHours: number, excludeId?: string) {
    const since = Date.now() - maxAgeHours * 3_600_000;
    const match = [...this.rows.values()]
      .filter((r) => r.fingerprint === fingerprint && statuses.includes(r.status) && r.id !== excludeId && Date.parse(r.updated_at) >= since)
      .sort((a, b) => Date.parse(b.updated_at) - Date.parse(a.updated_at))[0];
    return match ? this.clone(match) : null;
  }

  async listActive(limit: number) {
    return [...this.rows.values()]
      .filter((r) => (r.status === "running" && r.lease_until <= Date.now()) || (r.status === "ready" && r.email && !r.notified_at))
      .slice(0, limit)
      .map((r) => this.clone(r));
  }

  async setEmail(id: string, email: string, leadId: string | null) {
    const row = this.rows.get(id);
    if (!row) return false;
    row.email = email;
    row.lead_id = leadId;
    return true;
  }

  async markNotified(id: string) {
    const row = this.rows.get(id);
    if (!row || row.notified_at) return false;
    row.notified_at = new Date().toISOString();
    return true;
  }
}

const globalStore = globalThis as unknown as { __gcPreviewMemoryStore?: MemoryPreviewStore };

/**
 * The configured store. In production a missing Supabase configuration is a
 * hard stop (null): previews must survive the visitor closing the page.
 */
export function previewStore(): PreviewStore | null {
  const cfg = rpcConfig();
  if (cfg) return new SupabasePreviewStore(cfg);
  if (process.env.NODE_ENV === "production") return null;
  globalStore.__gcPreviewMemoryStore ??= new MemoryPreviewStore();
  return globalStore.__gcPreviewMemoryStore;
}
